language: node_js
env:
  global:
  - GH_REF=github.com/opengovt/openroads.git
  - DEPLOY_BRANCH=master
  - secure: "l2/pKIh0uT/pnEmPA36x4Pv4bhZVqooRBV+1NgBz/3mJ62koBxe6phK9LEcVGNXCoDpO7eHpHwKvmoNK+98GkTsEwlKD77DpiE5bpdKs35qoVEpEcRwcj6XPYWhlh1fBU4KwWRDGM7nAzxHmiWwBu3Lx0FW5SwacUHExLfejwIw="

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- echo No test specified

after_success:
- ./.build_scripts/deploy.sh
